name: 🚀 機能提案
description: 新しい機能を提案する
title: '[Feat]'
labels: ['enhancement']
body:
  - type: textarea
    id: what
    attributes:
      label: 必要だと思う機能の内容
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: この機能が必要と考えられる理由
    validations:
      required: true
  - type: textarea
    id: how_it_works
    attributes:
      label: この機能があった場合にどういう動きをするかの例